exportSAS <- function(x, nameTab, nameFile, nameScript, folder = getwd(), separator = ",", 
                      labelVar = TRUE, labelVal = FALSE, endofline = NULL, encoding = "") {
  oldPath <- getwd()
  setwd(folder)
  
  # manage end-of-line character
  if (is.null(endofline)) {
    if (.Platform$OS.type == "windows") endofline <- "CRLF" else
      if (.Platform$OS.type == "unix") endofline <- "LF"
  } else if (!endofline %in% c("CRLF","LF","CR"))
    stop("End-of-line parameter mispecified. Must be equal to CRLF, CR or LF.")
  
  # input list
  inputType <- sapply(x, class)
  if (!is.vector(inputType))
    inputType <- inputType[nrow(inputType),]
  inputT <- ifelse(inputType == "character", " $", "")
  inputList <- paste0(paste0(names(x), inputT), collapse = " \n ")
  
  # dealing with factor
  if (length(which(inputType == "factor")) > 0) {
    codeFmt <- " \n"
    codeFmt2 <- "FORMAT \n"
    listVarFac <- names(x)[inputType == "factor"]
    addCode <- function(...) paste0(codeFmt, ...)
    addCode2 <- function(...) paste0(codeFmt2, ...)
    for (v in 1:length(listVarFac)) {
      var <- listVarFac[v]
      lvls <-levels(x[, var])
      if (labelVal == TRUE) {
        codeFmt <- addCode("PROC FORMAT ; \n")
        codeFmt <- addCode("VALUE FMT", v, " \n")
        for (i in 1:length(lvls)) {
          codeFmt <- addCode("  ", i, " = \"", lvls[i], "\" \n")
        }
        codeFmt <- addCode("; \n RUN ; \n \n")
        codeFmt2 <- addCode2("  ", var, " FMT", v, ". \n")
      }
      x[, var] <- as.numeric(x[, var])
    }  
  }
  
  # dealing with the length of character variables
  varChar <- names(x)[inputType == "character"]
  maxLength <- function(x) return(apply(sapply(x,nchar), 2, max, na.rm = TRUE))
  length <- maxLength(x[,varChar])
  lengthList <- paste0(paste0(varChar, inputT[inputType == "character"], length, "."), 
                       collapse = "\n ")
  
  # dealing with variable labels
  if (labelVar == TRUE) {
    require(Hmisc)
    codeLbl <- "LABEL \n"
    addCode <- function(...) paste0(codeLbl, ...)
    listVar <- names(x)
    for (v in 1:length(listVar)) {
      var <- listVar[v]
      if (!label(x[,var]) %in% c(""," "))
        codeLbl <- addCode(var, " = \"", label(x[, var]), "\" \n")
    }
    codeLbl <- addCode(" ; \n")
  }
  
  # writing SAS script
  addCode <- function(...) paste0(code, ...)
  code <- "/* Codes generated by function exportSAS  */\n "
  code <- addCode("LIBNAME out \"", folder, "\" ; \n ")
  code <- addCode("\n ")
  if (labelVal == TRUE)
    code <- addCode(codeFmt)
  code <- addCode("DATA out.", nameTab, " ; \n ")
  code <- addCode("INFILE \"", folder, "/", nameFile, "\" DSD DLM = \"", separator, 
                  "\" TERMSTR = ", endofline," ; \n ")
  code <- addCode("LENGTH \n ", lengthList, "\n ; \n ")
  if (labelVal == TRUE)
    code <- addCode(codeFmt2, "; \n")
  code <- addCode("INPUT \n ")
  code <- addCode(inputList, " \n ; \n ")
  if (labelVar == TRUE)
    code <- addCode(codeLbl)
  code <- addCode("RUN ; \n ")
  
  write.table(x, file = nameFile, quote = FALSE, sep = separator, row.names = FALSE, 
              fileEncoding = encoding, na = "")
  
  # writing raw data
  write.table(code, file = nameScript, quote = FALSE, sep = "", row.names = FALSE, 
              col.names = FALSE, fileEncoding = encoding)
}