exportSAS <- function(x, nameTab, nameFile, nameScript, folder = getwd(), separator = ",", 
                      labelVar = TRUE, labelVal = FALSE, endofline = NULL, encoding = "") {
  oldPath <- getwd()
  setwd(folder)
  
  write.table(x, file = nameFile, quote = FALSE, sep = separator, row.names = FALSE, 
              fileEncoding = encoding, na = "")
  
  inputType <- sapply(x, class)
  inputT <- ifelse(inputType == "character", " $ ", "")
  inputList <- paste0(paste0(names(x), inputT), collapse = " \n ")
  
  addCode <- function(...) paste0(code, ...)
  code <- "/* Codes generated by function exportSAS \n "
  code <- addCode("LIBNAME out \"", folder, "\" ; \n ")
  code <- addCode("\n ")
  code <- addCode("DATA out.", nameTab, " ; \n ")
  code <- addCode("INFILE \"", folder, "/", nameFile, "\" DSD DLM = \"", separator, "\" ; \n ")
  code <- addCode("INPUT \n ")
  code <- addCode(inputList, " \n ; \n ")
  code <- addCode("RUN ; \n ")
  
  write.table(code, file = nameScript, quote = FALSE, sep = "", row.names = FALSE, 
              col.names = FALSE, fileEncoding = encoding)
}