exportSAS <- function(x, nameTab, nameFile, nameScript, folder = getwd(), separator = ",", 
                      labelVar = TRUE, labelVal = FALSE, endofline = NULL, encoding = "") {
  oldPath <- getwd()
  setwd(folder)
  
  write.table(x, file = nameFile, quote = FALSE, sep = separator, row.names = FALSE, 
              fileEncoding = encoding)
  
  addCode <- function(...) paste0(code, ...)
  code <- "/* Codes generated by function exportSAS \n "
  code <- addCode("LIBNAME out \"", folder, "\" ; \n ")
  code <- addCode("\n ")
  code <- addCode("DATA out.", nameTab, " ; \n ")
  code <- addCode("FILE \"", folder, "/", nameFile, "\" DSD DLM = \"", separator, "\" ; \n ")
  code <- addCode("RUN ; \n ")
}